# Generated by Django 4.0.3 on 2022-05-11 09:07

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cd_pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='change_detection/pic_path', verbose_name='用于变化检测的图片')),
            ],
            options={
                'verbose_name': '变化检测图片',
                'verbose_name_plural': '变化检测图片',
                'db_table': 'cd_img',
            },
        ),
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(null=True, upload_to=app.models.picture_directory_path, verbose_name='展示的图片')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
                'db_table': 'picture',
            },
        ),
    ]
