# Generated by Django 4.0.3 on 2022-06-06 03:19

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pic',
            options={'verbose_name': '示例图片', 'verbose_name_plural': '示例图片'},
        ),
        migrations.AlterField(
            model_name='pic',
            name='img',
            field=models.FileField(null=True, upload_to=app.models.picture_directory_path, verbose_name='示例图片'),
        ),
    ]
