# Generated by Django 4.0.3 on 2022-05-05 02:13

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_pic_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=app.models.picture_directory_path, verbose_name='图片'),
        ),
    ]
