# Generated by Django 4.0.3 on 2022-06-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_pic_options_alter_pic_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pic',
            old_name='img',
            new_name='image',
        ),
    ]
