# Generated by Django 4.0.3 on 2022-06-08 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_img_pic_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pic',
            old_name='image',
            new_name='image_url',
        ),
    ]
