# Generated by Django 4.0.3 on 2022-06-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_image_pic_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd_pic',
            name='img',
            field=models.ImageField(upload_to='change_detection/pic_path', verbose_name='用于变化检测的图片'),
        ),
    ]
