# Generated by Django 4.0.3 on 2022-06-09 06:47

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_cd_pic_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='image_url',
            field=models.ImageField(null=True, upload_to=app.models.picture_directory_path, verbose_name='示例图片'),
        ),
    ]
